# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        miniature_event:
            quality: 100
            filters:
                thumbnail: { size: [ 90, 60 ], mode: outbound }
        miniature_event_front:
            quality: 100
            filters:
                thumbnail: { size: [ 200, 200 ], mode: outbound }

    twig:
        mode: lazy